### ISSUE TITLE
Hack: allow users to update their data by repeating onboarding

### ISSUE THREAD

**Issue by w-dib** [Callmi-org/callmi#35]
If logged in as expert, they click “Edit profile” button on top right

user is then redirected to onboarding, except instead of “Welcome to Callmi” H1, it says “Update your Callmi details”

Data defaults to whatever current details are

It gets updated CRUD as and when user updates it.

All data gets updated on “Finish” button

User redirected to expert screen

**Comment by mo-shawa** [comment]
Issue will be addressed by #44
